# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "lovenery/vagrant-laravel"

  config.ssh.username = 'ubuntu'
  config.ssh.password = 'vagrant'

  config.vm.synced_folder "code/", "/vagrant", :group => 'www-data', mount_options: ['dmode=777','fmode=775']
  config.vm.network "private_network", ip: "192.168.33.10"
end
